---
title: "terrible_plot_day7"
format:
  html:
    theme: default
    toc: true
    number-sections: true
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(gapminder)
library(sf)
library(packcircles)
library(treemap)
```

```{r}
terrible_plot_SF <- read_csv(here::here("data", "San_Francisco_Communitywide_Greenhouse_Gas_Inventory.csv"))
```

geom_sf(data = jornada_veg, aes(fill = name), colour = NA) +

theme_minimal() +

scale_fill_paletteer_d(palette = "ggthemes::manyeys") +

theme(panel.background = element_rect(color = "purple", size = 5, fill = "pink"),

plot.background = element_rect(fill = "yellow"),

panel.grid.major = element_line(color = "magenta"),

axis.test.x = element_text(color = "red"))

```{r}
ggplot(data = terrible_plot_SF, aes(x = Sector_Detail2, y = Quantity)) +
  geom_point(fill = "green", shape = 23, color = "coral4" ) +
  facet_wrap(~ Commodity_Type, scales = "free")
  geom_hline(yintercept = 70000, linetype = "dotted", color = "purple")
  
               

```

```{r}
summary_greenhouse <- terrible_plot_SF %>%
  
```

```{r}
terrible_space <- read_csv(here::here("data", "space_launches.csv"))

```

```{r}
ggplot(map) +
  geom_sf(color = "white", aes(fill = unemp_rate)) +
  geom_sf_text(aes(label = name), size = 2) +
  theme(legend.position = "none")

```
